### ISSUE TITLE
Boomper no longer works on any of our repos

### ISSUE THREAD

**Issue by jessebye** [toolmantim/boomper#108]
Similar to https://github.com/SvanBoxel/delete-merged-branch/issues/198

Boomper is no longer working on any of our repos. We tried to debug on our side but have no visibility. @toolmantim can you take a look?

**Comment by toolmantim** [comment]
Sorry, Boomper went offline when Zeit deprecated v1.0 of their platform. I’m hoping to have it back up and running on Heroku soon. Ideally we could make it available via a GitHub Action too.

**Comment by toolmantim** [comment]
It's up and running again! Sorry it was down for a while.
